version: '3.3'
services:
  www:
    build: .
    ports: 
      - "80:80"
    volumes:
      - ./www:/var/www/
    links:
      - db:db

  db:
    image: mysql:5.7
    ports: 
      - "4406:3306"
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - persistent_brumadinho:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

volumes:
    persistent_brumadinho:
